version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30  # Use a CircleCI Android image with the required SDK version
    working_directory: ~/repo  t

jobs:
  build:
    executor: android-executor
    steps:
      - checkout  # Checkout the source code

      - run:
          name: Update SDKs
          command: sdkmanager "platforms;android-30" "build-tools;30.0.3"

      # Restore Gradle dependencies cache based on build.gradle.kts and settings.gradle.kts
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
            - v1-dependencies-

      # Ensure Gradle wrapper has executable permissions
      - run:
          name: Grant Gradle executable permissions
          command: chmod +x ./gradlew

      # Run Gradle clean and build
      - run:
          name: Gradle Clean
          command: ./gradlew clean

      - run:
          name: Gradle Build
          command: ./gradlew assembleDebug

      # Save Gradle cache after build
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}

  test:
    executor: android-executor
    steps:
      - checkout

      # Ensure Gradle wrapper has executable permissions before running tests
      - run:
          name: Grant Gradle executable permissions
          command: chmod +x ./gradlew

      - run:
          name: Gradle Test
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
