version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30  # Android image with SDK 30
    working_directory: ~/repo
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-temurin  # Corrected JAVA_HOME to match manual installation path
      _JAVA_OPTIONS: "-Xmx2048m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      # Add missing GPG key for Google Cloud SDK
      - run:
          name: Add GPG key for Google Cloud SDK
          command: |
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://packages.cloud.google.com/apt cloud-sdk-buster main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            sudo apt-get update

      # Install dependencies for Java installation
      - run:
          name: Install Required Packages
          command: |
            sudo apt-get install -y wget tar

      # Download and install Java 8 directly
      - run:
          name: Install Java 8 (Temurin)
          command: |
            wget -O temurin.tar.gz https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u372-b07/OpenJDK8U-jdk_x64_linux_hotspot_8u372b07.tar.gz
            sudo mkdir -p /usr/lib/jvm
            sudo tar -xzf temurin.tar.gz -C /usr/lib/jvm
            sudo mv /usr/lib/jvm/jdk8u372-b07 /usr/lib/jvm/java-8-temurin
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-temurin/bin/java 1
            sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-8-temurin/bin/javac 1
            sudo update-alternatives --set java /usr/lib/jvm/java-8-temurin/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-temurin/bin/javac
            echo "Java version set to:"
            java -version

      # Verify JAVA_HOME
      - run:
          name: Verify JAVA_HOME
          command: echo "JAVA_HOME is set to: ${JAVA_HOME}"

      # Update SDKs
      - run:
          name: Update SDKs
          command: sdkmanager "platforms;android-30" "build-tools;30.0.3"

      # Restore Gradle cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
            - v1-dependencies-

      # Ensure Gradle wrapper has executable permissions
      - run:
          name: Grant Gradle executable permissions
          command: chmod +x ./gradlew

      # Run Gradle clean and build
      - run:
          name: Gradle Clean
          command: ./gradlew clean

      - run:
          name: Gradle Build
          command: ./gradlew assembleDebug

      # Save Gradle cache after build
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}

  test:
    executor: android-executor
    steps:
      - checkout

      # Ensure Gradle wrapper has executable permissions
      - run:
          name: Grant Gradle executable permissions
          command: chmod +x ./gradlew

      - run:
          name: Gradle Test
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
