version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30  # Android image with SDK 30
    working_directory: ~/repo
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64  # Set JAVA_HOME to Java 8 path
      _JAVA_OPTIONS: "-Xmx2048m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      # Fix GPG Key Issue for Google Cloud SDK
      - run:
          name: Fix GPG Key Issue for Google Cloud SDK
          command: |
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update

      # Install Java 8
      - run:
          name: Install Java 8
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            echo "Java version set to:"
            java -version

      # Update SDKs
      - run:
          name: Update SDKs
          command: sdkmanager "platforms;android-30" "build-tools;30.0.3"

      # Restore Gradle cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
            - v1-dependencies-

      # Ensure Gradle wrapper has executable permissions
      - run:
          name: Grant Gradle executable permissions
          command: chmod +x ./gradlew

      # Run Gradle clean and build
      - run:
          name: Gradle Clean
          command: ./gradlew clean

      - run:
          name: Gradle Build
          command: ./gradlew assembleDebug

      # Save Gradle cache after build
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}

  test:
    executor: android-executor
    steps:
      - checkout

      # Ensure Gradle wrapper has executable permissions
      - run:
          name: Grant Gradle executable permissions
          command: chmod +x ./gradlew

      - run:
          name: Gradle Test
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
