version: 2.1
orbs:
  android: circleci/android@2.4.0

executors:
  android-executor:
    docker:
      - image: cimg/android:2024.09
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
            - v1-dependencies-
            
   # Ensure Gradle wrapper has executable permissions
      - run:
          name: Grant Gradle executable permissions
          command: chmod +x ./gradlew

      # Run Gradle clean and build
      - run:
          name: Gradle Clean
          command: ./gradlew clean

      - run:
          name: Gradle Build
          command: ./gradlew assembleDebug

      # Save Gradle cache after build
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
          
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: app-debug.apk
      - store_test_results:
          path: app/build/test-results

  test:
    executor: android-executor
    steps:
      - checkout

      # Ensure Gradle wrapper has executable permissions
      - run:
          name: Grant Gradle executable permissions
          command: chmod +x ./gradlew

      - run:
          name: Gradle Test
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
