version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30  # Use a CircleCI Android image with the required SDK version
    working_directory: ~/repo 

jobs:
  build:
    executor: android-executor
    steps:
      - checkout  # Checkout the source code

      - run:
          name: Update SDKs
          command: sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/build.gradle" }}-{{ checksum "app/src/build.gradle" }}
            - v1-dependencies-

      - run:
          name: Gradle Clean
          command: ./gradlew clean

      - run:
          name: Gradle Build
          command: ./gradlew assembleDebug

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-dependencies-{{ checksum "app/build.gradle" }}-{{ checksum "app/src/build.gradle" }}

  test:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Gradle Test
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

